### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by Anurag30112003** [Anurag30112003/codeAI#10]
Add dark mode feature
Will inherit system theme
With the dark mode toggle button

Can use the following resources -

https://tailwindcss.com/docs/dark-mode
https://egghead.io/blog/tailwindcss-dark-mode-nextjs-typography-prose

**Comment by Mustafa-Azad025** [comment]
hey @Anurag30112003 ,
please assign this task to me .

**Comment by Anurag30112003** [comment]
assigned @Mustafa-Azad025

**Comment by Mustafa-Azad025** [comment]
hi i am unable to Raise PR please Do something

**Comment by Anurag30112003** [comment]
You were having merge conflicts, I have resolved them. From next time sync your fork and do git pull before pushing to remote. 😄😄

**Comment by Mustafa-Azad025** [comment]
Thank you so much sir
