### ISSUE TITLE
Add placeholder to the form

### ISSUE THREAD

**Issue by Anurag30112003** [Anurag30112003/codeAI#2]
Add placeholder text for form input , to provide context on what is to be entered as input

**Comment by rutvikk05** [comment]
Hello, I would like to work on this issue. Could you please assign it to me?

**Comment by Anurag30112003** [comment]
Here you go @rutvikk05 . 😄

**Comment by Anurag30112003** [comment]
@rutvikk05 are working on this issue?

**Comment by rutvikk05** [comment]
Hey @Anurag30112003, yes I'm currently working on it. Thanks for assigning it to me :D

**Comment by rutvikk05** [comment]
update : sent you the PR
