### ISSUE TITLE
Make website responsive

### ISSUE THREAD

**Issue by Anurag30112003** [Anurag30112003/codeAI#31]
Make website responsive 
![image](https://user-images.githubusercontent.com/79055093/195177948-8e91886a-12a5-4fb1-972e-8a83d0d54896.png)

**Comment by syprogrammer** [comment]
can you assign me

**Comment by Anurag30112003** [comment]
@Cyber-Machine wanna work on this

**Comment by Anurag30112003** [comment]
ok assigned @syprogrammer

**Comment by syprogrammer** [comment]
@Anurag30112003 i have fixed this issue now it look like this : https://bit.ly/3TfPow4
is it ok

**Comment by Anurag30112003** [comment]
@syprogrammer Looks good , create a pull request , I'll take a look into it.
