### ISSUE TITLE
Add animation

### ISSUE THREAD

**Issue by Anurag30112003** [Anurag30112003/codeAI#32]
Add animations to the navbar and home page + tools page using Framer motion.

Read more about - https://www.framer.com/docs/

**Comment by Anurag30112003** [comment]
@Cyber-Machine wanna work on this ?

**Comment by prajjwalkapoor** [comment]
@Anurag30112003 can you assign me this?

**Comment by Anurag30112003** [comment]
ok , assigned @prajjwalkapoor
