### ISSUE TITLE
Improve responsiveness , of tools pages

### ISSUE THREAD

**Issue by Anurag30112003** [Anurag30112003/codeAI#38]
![image](https://user-images.githubusercontent.com/79055093/195983069-5ba53dcd-420f-41eb-a42d-8e36ead31ad6.png)
Make every tool [page] responsive.
Decrease the width of the text area.

**Comment by UditNS** [comment]
Hi @Anurag30112003, I want to work on this but you know text area size can be customised by bottom-right area so, I think first resizing need to be stop then we can set width according to the screen size.
