### ISSUE TITLE
Make a better navbar

### ISSUE THREAD

**Issue by Anurag30112003** [Anurag30112003/codeAI#7]

**Comment by detronetdip** [comment]
Can I work on this?

**Comment by Tusharjain123** [comment]
Hey @Anurag30112003, Can I work on this issue?

**Comment by Anurag30112003** [comment]
Yes anyone can work on this , let me know if you want to be assigned with this issue

**Comment by ahmedsilat44** [comment]
Hello @Anurag30112003 hello. Could you assign this to me, It is my first time contributing and taking part in hacktoberfest so I'd like to take on this task. Thanks 😃

**Comment by Anurag30112003** [comment]
Ok , assigned @ahmedsilat44 😄
